DROP DATABASE IF EXISTS SOA_REST;
CREATE DATABASE IF NOT EXISTS SOA_REST;
USE SOA_REST;


/* CREATE STUDENT TABLE */
SELECT 'CREATING STUDENT TABLE' as 'INFO';

DROP TABLE IF EXISTS student;

CREATE TABLE student (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    course VARCHAR(255) NOT NULL
);



SELECT 'INSERTING DATA INTO STUDENT' as 'INFO';

INSERT INTO student VALUES (NULL, 'Joe Bloggs', 'Athlone', 'Software Engineering');
INSERT INTO student VALUES (NULL, 'Jane Doe', 'Mullingar', 'Mechanical Engineering');


SELECT 'CHECKING TO SEE IF DATA INSERTED TO STUDENT CORRECTLY' as 'INFO';

SELECT * from student;
